// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sphere.Infrastructure.Models;

public partial class SPC_VN_OPTICSContext : DbContext
{
    public SPC_VN_OPTICSContext(DbContextOptions<SPC_VN_OPTICSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SpcUserInfo> SpcUserInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SpcUserInfo>(entity =>
        {
            entity.HasKey(e => new { e.DivSeq, e.UserId });

            entity.ToTable("SPC_USER_INFO");

            entity.HasIndex(e => new { e.DivSeq, e.RoleCode }, "IX_UserInfo_DivSeq_RoleCode");

            entity.HasIndex(e => e.Email, "IX_UserInfo_Email");

            entity.HasIndex(e => e.UseYn, "IX_UserInfo_UseYn");

            entity.Property(e => e.DivSeq)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("div_seq");
            entity.Property(e => e.UserId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("user_id");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.CreateUserId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("create_user_id");
            entity.Property(e => e.DeptCode)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("dept_code");
            entity.Property(e => e.DeptName)
                .HasMaxLength(100)
                .HasColumnName("dept_name");
            entity.Property(e => e.Email)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FailCount)
                .HasDefaultValue(0)
                .HasColumnName("fail_count");
            entity.Property(e => e.IsLocked)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("N")
                .HasColumnName("is_locked");
            entity.Property(e => e.Language)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("ko-KR")
                .HasColumnName("language");
            entity.Property(e => e.LastLoginDate)
                .HasColumnType("datetime")
                .HasColumnName("last_login_date");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.PositionCode)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("position_code");
            entity.Property(e => e.PositionName)
                .HasMaxLength(100)
                .HasColumnName("position_name");
            entity.Property(e => e.RoleCode)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("role_code");
            entity.Property(e => e.RoleName)
                .HasMaxLength(100)
                .HasColumnName("role_name");
            entity.Property(e => e.RowStatus)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ROW_STATUS");
            entity.Property(e => e.Timezone)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("Asia/Seoul")
                .HasColumnName("timezone");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("update_date");
            entity.Property(e => e.UpdateUserId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("update_user_id");
            entity.Property(e => e.UseYn)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("Y")
                .HasColumnName("use_yn");
            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .HasColumnName("user_name");
            entity.Property(e => e.UserNameE)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("user_name_e");
            entity.Property(e => e.UserNameK)
                .HasMaxLength(100)
                .HasColumnName("user_name_k");
        });
        modelBuilder.HasSequence("GetMaterialSeq");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}