// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sphere.Infrastructure.Models;

public partial class SpcUserInfo
{
    public string DivSeq { get; set; }

    public string UserId { get; set; }

    public string PasswordHash { get; set; }

    public string UserName { get; set; }

    public string UserNameK { get; set; }

    public string UserNameE { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string DeptCode { get; set; }

    public string DeptName { get; set; }

    public string PositionCode { get; set; }

    public string PositionName { get; set; }

    public string RoleCode { get; set; }

    public string RoleName { get; set; }

    public string Language { get; set; }

    public string Timezone { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public string IsLocked { get; set; }

    public int? FailCount { get; set; }

    public string UseYn { get; set; }

    public string RowStatus { get; set; }

    public string CreateUserId { get; set; }

    public DateTime? CreateDate { get; set; }

    public string UpdateUserId { get; set; }

    public DateTime? UpdateDate { get; set; }
}